name: Docs

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
  
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - run: julia --project=docs -e 'using Pkg; Pkg.instantiate()'
      - run: julia --project=docs docs/make.jl
        env:
          GKSwstype: nul
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
